POST http://localhost:4000/api/westcon/create-ticket
Content-Type: application/json

{
  "name": "Rucci",
  "email": "rucci@gmail.com",
  "phoneNumber": "08123456789",
  "ticket": "T-123",
  "notify": false
}